services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mysql-master
      - mysql-node1
      - mysql-node2
    networks:
      - game-network

  mysql-master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: steamgames
    ports:
      - "3307:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - game-network

  mysql-node1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: steamgames
    ports:
      - "3308:3306"
    volumes:
      - mysql-node1-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - game-network

  mysql-node2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: steamgames
    ports:
      - "3309:3306"
    volumes:
      - mysql-node2-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

volumes:
  mysql-master-data:
  mysql-node1-data:
  mysql-node2-data:
